"""Attack vectors and orchestration."""

from .amplification import (
    AmplificationAttack,
    DNSAmplification,
    NTPAmplification,
    SSDPAmplification,
    MemcachedAmplification,
    ChargenAmplification,
    SNMPAmplification,
)
from .layer7 import (
    Layer7Attack,
    HTTPFlood,
    SlowlorisAttack,
    SlowPOST,
    RUDYAttack,
    HTTPSmuggling,
    CacheBypass,
)
from .connection import (
    ConnectionExhaustion,
    SYNFlood,
    ACKFlood,
    RSTFlood,
    FINFlood,
    XMASFlood,
    NullScan,
    PushAckFlood,
    SYNACKFlood,
)

try:
    from core.native_engine import (
        SSLExhaustion,
        SSLRenegotiation,
        HeartbleedTest,
        THCSSLDoS,
    )
except ImportError:

    class SSLExhaustion:
        def __init__(self, config=None):
            pass

    class SSLRenegotiation:
        def __init__(self, config=None):
            pass

    class HeartbleedTest:
        def __init__(self):
            pass

    class THCSSLDoS:
        def __init__(self, config=None):
            pass


from .protocol_specific import (
    DNSFlood,
    SMTPFlood,
    FTPBounce,
    SSHBruteforce,
    MySQLFlood,
    RedisFlood,
)
from .application import (
    WordPressAttack,
    APIFlood,
    WebSocketFlood,
    GraphQLAttack,
)
from .payload_generator import (
    PayloadGenerator,
    PayloadFactory,
    PayloadType,
    PayloadConfig,
    RandomPayload,
    PatternPayload,
    PolymorphicPayload,
    FuzzingPayload,
    ProtocolPayload,
    EvasionPayload,
)
from .orchestrator import (
    AttackOrchestrator,
    MultiTargetOrchestrator,
    AttackConfig,
    AttackPhase,
    AttackVector,
)
from .adaptive import (
    AdaptiveController,
    AdaptiveAttackEngine,
    AdaptiveConfig,
    AdaptationStrategy,
    TargetState,
    ResponseAnalyzer,
    PatternLearner,
    MultiStrategyAdapter,
)
from .botnet_sim import (
    BotState,
    CommandType,
    BotConfig,
    Command,
    SimulatedBot,
    BotnetController,
    HierarchicalBotnet,
    AttackWave,
)
from .attack_chains import (
    ChainResult,
    AttackStage,
    ChainConfig,
    AttackStep,
    StepResult,
    AttackExecutor,
    RealFloodExecutor,
    SimulatedExecutor,
    AttackChain,
    ParallelChain,
    ConditionalChain,
    EscalationChain,
    ChainBuilder,
)
from .steganography import (
    StegoMethod,
    StegoConfig,
    StegoEncoder,
    LSBEncoder,
    WhitespaceEncoder,
    UnicodeEncoder,
    ProtocolHeaderEncoder,
    TimingEncoder,
    StegoFactory,
    CovertChannel,
)
from .timing_attacks import (
    TimingPattern,
    TimingConfig,
    TimingGenerator,
    SlowRateAttack,
    SlowlorisAdvanced,
    ResourceExhaustionTiming,
    SynchronizedTimingAttack,
    TimingSideChannel,
)
from .mutation_engine import (
    MutationType,
    MutationConfig,
    Individual,
    FitnessFunction,
    EntropyFitness,
    UniqueFitness,
    SizeFitness,
    CompositeFitness,
    MutationOperator,
    CrossoverOperator,
    MutationEngine,
    AdaptiveMutationEngine,
)
from .protocol_fuzzer import (
    FuzzStrategy,
    FuzzConfig,
    FuzzResult,
    CrashInfo,
    ProtocolGrammar,
    Mutator,
    ProtocolFuzzer,
    HTTPFuzzer,
    DNSFuzzer,
    TCPFuzzer,
    create_fuzzer,
)
from .advanced_vectors import (
    AttackCategory,
    AttackWaveConfig,
    PayloadEngine,
    EvasionEngine,
    MultiVectorAttack,
    AdaptiveAttackController,
    ATTACK_PROFILES,
    get_attack_profile,
)
from .layer4 import (
    Layer4Config,
    Layer4Stats,
    IPSpoofing,
    Layer4Attack,
    UDPFlood,
    TCPFlagAttack,
    ICMPFlood,
    TCPConnectionExhaustion,
    create_udp_flood,
    create_syn_flood,
    create_ack_flood,
    create_rst_flood,
    create_fin_flood,
    create_icmp_flood,
    create_xmas_flood,
    create_null_flood,
    create_push_ack_flood,
    create_syn_ack_flood,
    create_connection_exhaustion,
    create_ping_flood,
    create_icmp_unreachable_flood,
    create_icmp_timestamp_flood,
    create_icmp_redirect_flood,
    LAYER4_ATTACK_PROFILES,
    get_attack_profile as get_layer4_profile,
)
from .vector_selector import VectorType, VectorRecommendation, ServiceVectorMapper
from .effectiveness_monitor import (
    DefenseState,
    ResponseMetrics,
    EffectivenessStats,
    EffectivenessMonitor,
)
from .intelligent_selector import (
    CampaignPhase,
    IntensityLevel,
    CampaignConfig,
    AdaptationEvent,
    IntelligentVectorSelector,
)

__all__ = [
    "AmplificationAttack",
    "DNSAmplification",
    "NTPAmplification",
    "SSDPAmplification",
    "MemcachedAmplification",
    "ChargenAmplification",
    "SNMPAmplification",
    "Layer7Attack",
    "HTTPFlood",
    "SlowlorisAttack",
    "SlowPOST",
    "RUDYAttack",
    "HTTPSmuggling",
    "CacheBypass",
    "ConnectionExhaustion",
    "SYNFlood",
    "ACKFlood",
    "RSTFlood",
    "FINFlood",
    "XMASFlood",
    "NullScan",
    "PushAckFlood",
    "SYNACKFlood",
    "SSLExhaustion",
    "SSLRenegotiation",
    "HeartbleedTest",
    "THCSSLDoS",
    "DNSFlood",
    "SMTPFlood",
    "FTPBounce",
    "SSHBruteforce",
    "MySQLFlood",
    "RedisFlood",
    "WordPressAttack",
    "APIFlood",
    "WebSocketFlood",
    "GraphQLAttack",
    "PayloadGenerator",
    "PayloadFactory",
    "PayloadType",
    "PayloadConfig",
    "RandomPayload",
    "PatternPayload",
    "PolymorphicPayload",
    "FuzzingPayload",
    "ProtocolPayload",
    "EvasionPayload",
    "AttackOrchestrator",
    "MultiTargetOrchestrator",
    "AttackConfig",
    "AttackPhase",
    "AttackVector",
    "AdaptiveController",
    "AdaptiveAttackEngine",
    "AdaptiveConfig",
    "AdaptationStrategy",
    "TargetState",
    "ResponseAnalyzer",
    "PatternLearner",
    "MultiStrategyAdapter",
    "BotState",
    "CommandType",
    "BotConfig",
    "Command",
    "SimulatedBot",
    "BotnetController",
    "HierarchicalBotnet",
    "AttackWave",
    "ChainResult",
    "AttackStage",
    "ChainConfig",
    "AttackStep",
    "StepResult",
    "AttackExecutor",
    "RealFloodExecutor",
    "SimulatedExecutor",
    "AttackChain",
    "ParallelChain",
    "ConditionalChain",
    "EscalationChain",
    "ChainBuilder",
    "StegoMethod",
    "StegoConfig",
    "StegoEncoder",
    "LSBEncoder",
    "WhitespaceEncoder",
    "UnicodeEncoder",
    "ProtocolHeaderEncoder",
    "TimingEncoder",
    "StegoFactory",
    "CovertChannel",
    "TimingPattern",
    "TimingConfig",
    "TimingGenerator",
    "SlowRateAttack",
    "SlowlorisAdvanced",
    "ResourceExhaustionTiming",
    "SynchronizedTimingAttack",
    "TimingSideChannel",
    "MutationType",
    "MutationConfig",
    "Individual",
    "FitnessFunction",
    "EntropyFitness",
    "UniqueFitness",
    "SizeFitness",
    "CompositeFitness",
    "MutationOperator",
    "CrossoverOperator",
    "MutationEngine",
    "AdaptiveMutationEngine",
    "FuzzStrategy",
    "FuzzConfig",
    "FuzzResult",
    "CrashInfo",
    "ProtocolGrammar",
    "Mutator",
    "ProtocolFuzzer",
    "HTTPFuzzer",
    "DNSFuzzer",
    "TCPFuzzer",
    "create_fuzzer",
    "AttackCategory",
    "AttackWaveConfig",
    "PayloadEngine",
    "EvasionEngine",
    "MultiVectorAttack",
    "AdaptiveAttackController",
    "ATTACK_PROFILES",
    "get_attack_profile",
    "Layer4Config",
    "Layer4Stats",
    "IPSpoofing",
    "Layer4Attack",
    "UDPFlood",
    "TCPFlagAttack",
    "ICMPFlood",
    "TCPConnectionExhaustion",
    "create_udp_flood",
    "create_syn_flood",
    "create_ack_flood",
    "create_rst_flood",
    "create_fin_flood",
    "create_icmp_flood",
    "create_xmas_flood",
    "create_null_flood",
    "create_push_ack_flood",
    "create_syn_ack_flood",
    "create_connection_exhaustion",
    "create_ping_flood",
    "create_icmp_unreachable_flood",
    "create_icmp_timestamp_flood",
    "create_icmp_redirect_flood",
    "LAYER4_ATTACK_PROFILES",
    "get_layer4_profile",
    "VectorType",
    "VectorRecommendation",
    "ServiceVectorMapper",
    "DefenseState",
    "ResponseMetrics",
    "EffectivenessStats",
    "EffectivenessMonitor",
    "CampaignPhase",
    "IntensityLevel",
    "CampaignConfig",
    "AdaptationEvent",
    "IntelligentVectorSelector",
]
